export PATH="$PATH:/usr/local/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:$HOME/.rvm/bin"

#ALIASES
source ~/.zsh_aliases

# PLUGINS

# ANTIGEN
source ~/.zsh/plugins/antigen/antigen.zsh

antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle colorize

antigen apply

# autojump

[ -f /usr/local/etc/profile.d/autojump.sh  ] && . /usr/local/etc/profile.d/autojump.sh

# fuzzy finder

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh-history-substring-search

zmodload zsh/terminfo
bindkey "$terminfo[cuu1]" history-substring-search-up
bindkey "$terminfo[cud1]" history-substring-search-down

# Plugins

plugins=( zsh-syntax-highlighting )

# History

HISTFILE=~/.zsh_history
SAVEHIST=1000
HISTSIZE=1000
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

# RVM

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Base16 Shell

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Prompt

autoload -U promptinit && promptinit
prompt pure

# Project exports

for file in ~/.zsh/exports/*; do
  source "$file"
done

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export NVM_DIR="/Users/jamesvaughan/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
