# ALIASES
source ~/.zsh_aliases

# PROMPT
autoload -U promptinit && promptinit
prompt pure

# PLUGINS

# ANTIGEN
source ~/.zsh/plugins/antigen/antigen.zsh

antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle colorize

antigen apply

# autojump

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh

# fuzzy finder

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh-history-substring-search

zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
